language: node_js
sudo: true
node_js:
  - "7.10.0"
  - "6.10.3"
install:
  - npm install
  - bower install
before_script:
  - sudo npm install -g gulp gulp-cli
  - sudo npm install -g bower
script:
  - gulp userref
  - nodejs index.js